### ISSUE TITLE
RuntimeError: Unable to find installation candidates for jdk4py (11.0.13.1)

### ISSUE THREAD

**Issue by mpclarkson** [atoti/project-template#115]
When running `poetry install` I receive this error. I can replicate this on a Mac M1, Mac intel and in Docker.

**Comment by tibdex** [comment]
Hi Matthew, I work on MacBook with an Intel CPU and can install `jdk4py` 11 without issues.

For M1 it's understandable that it doesn't work because we can't list the ARM architecture [there](https://github.com/atoti/jdk4py/blob/1681f95e65d0cdfcae78f460989dc7fb220ffc9f/.github/workflows/deployment.yaml#L13) until https://github.com/actions/virtual-environments/issues/2187 is done.

- Can you share the errors you're getting on the different architecture you tried?
- Can you please also try installing `jdk4py` 17 on these platforms with this command:
   ```bash
   poetry new jdk4py-test && cd jdk4py-test && poetry add jdk4py
   ```

**Comment by mpclarkson** [comment]
Ah sorry. Turns out the Macbook Air I used to check this error in the office was also an M1, when I thought it was an Intel. My mistake. I'll close this issue now. Love your work.
